version: '3.8'

services:
  medical-api:
    container_name: medical.api.dev
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - medical-network
    depends_on:
      - medical-db
  medical-db:
    container_name: medical.postgres
    image: postgres:14
    networks:
      - medical-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  medical-adminer:
    container_name: medical.adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - medical-db
    networks:
      - medical-network
networks:
  medical-network:
volumes:
  pgdata: