version: '3.8'

services:
  medical-api:
    image: api-medical-api:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - medical-network
    depends_on:
      - medical-db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
  medical-db:
    image: postgres:14
    networks:
      - medical-network
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
  medical-adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - medical-db
    networks:
      - medical-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
networks:
  medical-network:
    driver: overlay
    attachable: true
volumes:
  pgdata: